### ISSUE TITLE
😊Can we cut a release since this is `v1.0` compatible?

### ISSUE THREAD

**Issue by NHDaly** [vtjnash/Glob.jl#16]
Glob now fails on julia `v1.0` unless you `pkg> add Glob#master`. Can we cut a version release? :)

Thanks!

**Comment by vtjnash** [comment]
I think it needs the travis and appveyor scripts replaced with the 1.0 versions of them, then I can tag a release.

**Comment by NHDaly** [comment]
Replace which with 1.0? Replace 0.6 with 1.0?

Leave 1.0 and nightly? Or keep 0.6, 1.0, and nightly for now?

**Comment by vtjnash** [comment]
Just keep 1.0 and nightly is enough. I think there's new AV scripts (https://discourse.julialang.org/t/ann-improved-appveyor-scripts/12754) and that the travis `language: julia` script has changed and so this one needs to be redone.

**Comment by NHDaly** [comment]
Opened #16

**Comment by NHDaly** [comment]
Okay cool, i switched to the newer AV script. It sounds like travis is working okay with no changes needed, but i might be wrong:
https://discourse.julialang.org/t/travis-and-julia-1-0/13166/12?u=nhdaly

**Comment by vtjnash** [comment]
Closed by #17, and released version v1.2.0

**Comment by NHDaly** [comment]
👍 thanks! :)

**Comment by NHDaly** [comment]
(I don't see an auto-generated PR on METADATA... Is this repo using Attobot? If not, can/should I use PkgDev to submit it to METADATA?)
https://github.com/JuliaLang/METADATA.jl/pulls?utf8=%E2%9C%93&q=%22glob.jl+%22

**Comment by vtjnash** [comment]
Thanks for checking, yeah, I just tagged it wrong. I recreated the tag and all is OK now (
https://github.com/JuliaLang/METADATA.jl/pull/16850)

**Comment by NHDaly** [comment]
:) thanks!
