### ISSUE TITLE
[PkgEval] Glob may have a testing issue on Julia 0.4 (2014-10-24)

### ISSUE THREAD

**Issue by IainNZ** [vtjnash/Glob.jl#3]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.4
* On **2014-10-23** the testing status was `Tests pass.`
* On **2014-10-24** the testing status changed to `Tests fail, but package loads.`

`Tests pass.` means that PackageEvaluator found the tests for your package, executed them, and they all passed.

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("Glob")' log
INFO: Installing Glob v1.0.1
INFO: Package database updated

>>> 'using Glob' log
Julia Version 0.4.0-dev+1270
Commit a6a6aa7 (2014-10-23 22:39 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log

WARNING: deprecated syntax "{a,b, ...}" at /home/idunning/pkgtest/.julia/v0.4/Glob/test/runtests.jl:1.
Use "Any[a,b, ...]" instead.

WARNING: isblank(c::Char) is deprecated, use c == ' ' || c == '\ \t' instead.
 in isblank at deprecated.jl:26
 in _match_bracket at /home/idunning/pkgtest/.julia/v0.4/Glob/test/../src/Glob.jl:147
 in _match at /home/idunning/pkgtest/.julia/v0.4/Glob/test/../src/Glob.jl:217
 in ismatch at /home/idunning/pkgtest/.julia/v0.4/Glob/test/../src/Glob.jl:73
 in anonymous at test.jl:85
 in do_test at test.jl:47
 in include at ./boot.jl:242
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:293
 in _start at ./client.jl:362
 in _start_3B_3764 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
ERROR: string test failed:
original: Glob.GlobMatch({"base",r"h.+"})

stringify: Glob.GlobMatch(Any["base",r"h.+"])
 in error at error.jl:21
 in test_string at /home/idunning/pkgtest/.julia/v0.4/Glob/test/runtests.jl:176
 in include at ./boot.jl:242
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:293
 in _start at ./client.jl:362
 in _start_3B_3764 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/Glob/test/runtests.jl, in expression starting on line 181

INFO: Testing Glob
================================[ ERROR: Glob ]=================================

failed process: Process(`/home/idunning/julia04/usr/bin/julia /home/idunning/pkgtest/.julia/v0.4/Glob/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: Glob had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:719
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:68
 in process_options at ./client.jl:221
 in _start at ./client.jl:362
 in _start_3B_3764 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so

>>> end of log
```

**Comment by vtjnash** [comment]
This was fixed in PR #5, just forgot to close the issue
